### ISSUE TITLE
Sidebar unstyled

### ISSUE THREAD

**Issue by rostislavjadavan** [natew/batsignal#1]
Hi netew,

Thank you for creating the eye candy theme! However, I have come across two minor issues that I wanted to bring to your attention:

- The sidebar isn't styled properly.
- The bottom left button ("Open a Remote Windows") also needs some styling.

I hope this feedback helps you improve the theme! Thanks!

<img width="1947" alt="image" src="https://github.com/natew/batsignal/assets/8955363/11b59d26-cb2b-4e80-9255-4654975c7153">

**Application information:**
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T15:00:40.428Z (2 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by natew** [comment]
fixed 0.0.3

**Comment by rostislavjadavan** [comment]
Thanks! 👍
